/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WarTeamPlayer = IDL.Record({
  'name' : IDL.Text,
  'rank' : IDL.Text,
  'role' : IDL.Text,
});
export const StaffMember = IDL.Record({
  'status' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const WarLog = IDL.Record({
  'map' : IDL.Text,
  'result' : IDL.Text,
  'date' : IDL.Int,
  'score' : IDL.Text,
  'notes' : IDL.Text,
  'opponent' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAsWarTeam' : IDL.Func([], [IDL.Vec(WarTeamPlayer)], ['query']),
  'getEuWarTeam' : IDL.Func([], [IDL.Vec(WarTeamPlayer)], ['query']),
  'getStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'getWarLogs' : IDL.Func([], [IDL.Vec(WarLog)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WarTeamPlayer = IDL.Record({
    'name' : IDL.Text,
    'rank' : IDL.Text,
    'role' : IDL.Text,
  });
  const StaffMember = IDL.Record({
    'status' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const WarLog = IDL.Record({
    'map' : IDL.Text,
    'result' : IDL.Text,
    'date' : IDL.Int,
    'score' : IDL.Text,
    'notes' : IDL.Text,
    'opponent' : IDL.Text,
  });
  
  return IDL.Service({
    'getAsWarTeam' : IDL.Func([], [IDL.Vec(WarTeamPlayer)], ['query']),
    'getEuWarTeam' : IDL.Func([], [IDL.Vec(WarTeamPlayer)], ['query']),
    'getStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'getWarLogs' : IDL.Func([], [IDL.Vec(WarLog)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };