/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface StaffMember {
  'status' : string,
  'name' : string,
  'role' : string,
}
export interface WarLog {
  'map' : string,
  'result' : string,
  'date' : bigint,
  'score' : string,
  'notes' : string,
  'opponent' : string,
}
export interface WarTeamPlayer {
  'name' : string,
  'rank' : string,
  'role' : string,
}
export interface _SERVICE {
  'getAsWarTeam' : ActorMethod<[], Array<WarTeamPlayer>>,
  'getEuWarTeam' : ActorMethod<[], Array<WarTeamPlayer>>,
  'getStaffMembers' : ActorMethod<[], Array<StaffMember>>,
  'getWarLogs' : ActorMethod<[], Array<WarLog>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];